# Configurando Servidor
server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost/comercial
    username: root
    password: 9330923a
    driver-class-name: com.mysql.jdbc.Driver
    #jndi-name: java:/comp/env/jdbc/readingListDS